### ISSUE TITLE
[select2sortable]

### ISSUE THREAD

**Issue by Cappue** [thrace-project/form-bundle#4]
In /Thrace/FormBundle/Form/DataTransformer/ArrayCollectionToStringTransformer.php Line 114 
....
$referenceObject->setProject($inversedObject);
....

setProject() is for demo,  shouldn't be something like that ?

$setInversedProperty = sprintf('set%s',ucfirst($this->inversedProperty));
$referenceObject->{$setInversedProperty}($inversedObject);

**Comment by zender** [comment]
Yes correct. 
I will fix it soon or may be you can fix it?
